:Author: ard12sgf1960
:Email: {AuthorEmail}
:Date: 22/12/2022
:Revision: version#
:License: Public Domain

= Project: {ESP32_WiFiManager_Basic.ino}

This project uses the WiFimanager library to allow the ESP32 to connect
to any network by scanning available connections
and allowing the user to select an access point
and provide the password to connect

This removes the need to hard-code the credentials

The library will also remember the network for automatic reconnection 

== Step 1: Installation

1. Download the WiFiManager library 
2. Load the ESP32_WiFiManager_Basic.ino file to the board 
3. Check your device for the WiFi network ESP32_Test
4. Select Connect to Network
5. Your device will present the log in screen
6. Select your network and provide the password
7. You're now connected 

== Step 2: Assemble the circuit

No assembly required

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
ESP32_WiFiManager_Basic           => Arduino sketch folder
  ├── ESP32_WiFiManager_Basic.ino => main Arduino file
  └── ReadMe.adoc                 => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact ard12sgf1960 https://id.arduino.cc/ard12sgf1960

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Qty | Website 
| B1 | ESP32 WROOM    | SKU ADA3269 | 1   | https://thepihut.com/products/espressif-esp32-development-board-developer-edition
| C1 | USB 2 Cable    |             | 1   | Amazon or eBay
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
